web:
    build: .
    dockerfile: web.dockerfile
    ports:
        - 8002:80
    volumes:
        - ./web:/web
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    build: .
    dockerfile: php.dockerfile
    volumes:
        - ./web:/web
    links:
        - db:mysql
db:
    build: .
    dockerfile: db.dockerfile
    ports:
        - 4002:3306
    volumes:
        - ./db:/var/lib/mysql
        - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
        - MYSQL_ROOT_PASSWORD=denenajs
        - MYSQL_USER=fridgemaster
        - MYSQL_PASSWORD=inafridge
        - MYSQL_DATABASE=bfridged
